name: CollisionLogger
author: fubira
website: ironingot.net 
main: net.ironingot.collisionlogger.CollisionLogger
version: 0.1
commands:
  clog:
    usage:
      /<command> [on|off]
      /<command> broadcast [on|off]
      /<command> version
    description: collision logger
